name       : nomad
version    : 1.1.6
release    : 5
source     :
    - https://github.com/hashicorp/nomad/archive/refs/tags/v1.1.6.tar.gz : e453570f9db84a13ae83bc813c94f6abe3010f39bd9814af5dbba28db19c44c7
license    : MPL-2.0
component  : virt
summary    : Nomad is a simple and flexible workload orchestrator
description: |
    Nomad is a simple and flexible workload orchestrator to deploy and manage containers (docker, podman), non-containerized applications (executable, Java), and virtual machines (qemu) across on-prem and clouds at scale.
networking : yes
builddeps  :
    - git
    - golang
setup      : |
    %make deps
build      : |
    %make dev
install    : |
    install -Dm00755 bin/nomad $installdir/usr/bin/nomad
