name       : nomad
version    : 1.2.3
release    : 7
source     :
    - git|https://github.com/hashicorp/nomad.git : v1.2.3
license    : MPL-2.0
component  : virt
summary    : Nomad is a simple and flexible workload orchestrator
description: |
    Nomad is a simple and flexible workload orchestrator to deploy and manage containers (docker, podman), non-containerized applications (executable, Java), and virtual machines (qemu) across on-prem and clouds at scale.
networking : yes
builddeps  :
    - git
    - golang
environment: |
    export GOPATH=$workdir/../
    export PATH=$PATH:$GOPATH/bin/
setup      : |
    %make deps
build      : |
    %make dev
install    : |
    install -Dm00755 bin/nomad $installdir/usr/bin/nomad
