name       : nomad
version    : 1.1.5
release    : 4
source     :
    - https://github.com/hashicorp/nomad/archive/refs/tags/v1.1.5.tar.gz : 7faa2e395ccbe53f5c2200b3ff8ace1430ae30e95f3a6c9673898413899eeda7
license    : MPL-2.0
component  : virt
summary    : Nomad is a simple and flexible workload orchestrator
description: |
    Nomad is a simple and flexible workload orchestrator to deploy and manage containers (docker, podman), non-containerized applications (executable, Java), and virtual machines (qemu) across on-prem and clouds at scale.
networking : yes
builddeps  :
    - git
    - golang
setup      : |
    %make deps
build      : |
    %make dev
install    : |
    install -Dm00755 bin/nomad $installdir/usr/bin/nomad
