name       : nomad
version    : 1.1.3
release    : 2
source     :
    - https://github.com/hashicorp/nomad/archive/refs/tags/v1.1.3.tar.gz : 18eb2b7fcd4d32952546b3d8b052e755dedc4c63e36527404db6abdce01b197d
license    : MPL-2.0
component  : virt
summary    : Nomad is a simple and flexible workload orchestrator
description: |
    Nomad is a simple and flexible workload orchestrator to deploy and manage containers (docker, podman), non-containerized applications (executable, Java), and virtual machines (qemu) across on-prem and clouds at scale.
networking : yes
builddeps  :
    - git
    - golang
setup      : |
    %make deps
build      : |
    %make dev
install    : |
    install -Dm00755 bin/nomad $installdir/usr/bin/nomad
